name: stroke-utilities-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.21.0
  - pandas
  - pip
  - python
  - importlib_resources
  - shap
  - xgboost
  - pip:
    - jupyterlab
    - setuptools
    - twine
    - wheel
    - stroke-outcome
